# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

check_csv <- function(path, is_compressed, parallel) {
    .Call(`_alabaster_base_check_csv`, path, is_compressed, parallel)
}

check_list_hdf5 <- function(file, name, num_external) {
    .Call(`_alabaster_base_check_list_hdf5`, file, name, num_external)
}

check_list_json <- function(file, num_external, parallel) {
    .Call(`_alabaster_base_check_list_json`, file, num_external, parallel)
}

load_csv <- function(path, is_compressed, nrecords, parallel) {
    .Call(`_alabaster_base_load_csv`, path, is_compressed, nrecords, parallel)
}

load_list_hdf5 <- function(file, name, obj) {
    .Call(`_alabaster_base_load_list_hdf5`, file, name, obj)
}

load_list_json <- function(file, obj, parallel) {
    .Call(`_alabaster_base_load_list_json`, file, obj, parallel)
}

write_integer_scalar <- function(path, host, name, val) {
    .Call(`_alabaster_base_write_integer_scalar`, path, host, name, val)
}

write_string_scalar <- function(path, host, name, val) {
    .Call(`_alabaster_base_write_string_scalar`, path, host, name, val)
}

