# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

check_csv <- function(path, is_compressed, parallel) {
    .Call(`_alabaster_base_check_csv`, path, is_compressed, parallel)
}

check_list <- function(contents) {
    .Call(`_alabaster_base_check_list`, contents)
}

load_csv <- function(path, is_compressed, nrecords, parallel) {
    .Call(`_alabaster_base_load_csv`, path, is_compressed, nrecords, parallel)
}

load_list <- function(contents, obj) {
    .Call(`_alabaster_base_load_list`, contents, obj)
}

